// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `atomic_write`, `base64_decode`, `base64_encode`, `build_eth_wallet`, `cache_mnemonic`, `cached_mnemonic`, `clear_mnemonic_cache`, `derive_kek`, `load_mnemonic_encrypted`, `map_eth_network`, `mnemonic_cache`, `mnemonic_sidecar_path`, `persist_mnemonic_encrypted`, `u256_from_dec_str`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EncryptedMnemonicBlob`, `KdfParams`

/// Returns the canonical EIP-55 address for the given EVM network. Re-derives
/// from the cached mnemonic on every call — keeps no on-disk ETH secret.
Future<String> argosEthAddress({required String network}) =>
    RustLib.instance.api.crateApiWalletEthApiArgosEthAddress(network: network);

/// Native balance in wei, returned as a decimal string (U256 may exceed u64).
Future<String> argosEthBalanceWei({required String network}) => RustLib
    .instance
    .api
    .crateApiWalletEthApiArgosEthBalanceWei(network: network);

/// ERC-20 token balance (raw, no decimals applied). Decimal string.
Future<String> argosEthErc20Balance({
  required String network,
  required String token,
}) => RustLib.instance.api.crateApiWalletEthApiArgosEthErc20Balance(
  network: network,
  token: token,
);

/// Send `wei` (decimal-string) of the network's native token to `recipient`.
/// Returns the tx-hash (`0x…`) the node accepted for broadcast.
Future<String> argosEthSendNative({
  required String network,
  required String recipient,
  required String wei,
}) => RustLib.instance.api.crateApiWalletEthApiArgosEthSendNative(
  network: network,
  recipient: recipient,
  wei: wei,
);

/// ERC-20 transfer. `amount` is decimal-string of raw token base units.
Future<String> argosEthSendErc20({
  required String network,
  required String token,
  required String recipient,
  required String amount,
}) => RustLib.instance.api.crateApiWalletEthApiArgosEthSendErc20(
  network: network,
  token: token,
  recipient: recipient,
  amount: amount,
);

/// UI helper: format a wei decimal-string as a 4-decimal ETH string.
Future<String> argosEthFormat({required String wei}) =>
    RustLib.instance.api.crateApiWalletEthApiArgosEthFormat(wei: wei);

/// Validate a user-pasted Ethereum address. Accepts checksummed or
/// lower-case hex. Returns the EIP-55 form on success.
Future<String> argosEthValidateAddress({required String s}) =>
    RustLib.instance.api.crateApiWalletEthApiArgosEthValidateAddress(s: s);

/// Securely delete the encrypted mnemonic sidecar for the given Solana
/// storage path. MUST be called from the Dart wipe() path — otherwise the
/// recovery phrase survives a wallet wipe (including the 10-try panic-wipe)
/// because wallet_service.dart only deletes the Solana keypair blob.
///
/// Uses the same [mnemonic_sidecar_path] derivation as persist/load so the
/// path can never drift between write and delete. Also clears the in-memory
/// mnemonic cache. Idempotent — returns Ok even if the sidecar was absent.
Future<void> argosWipeMnemonicSidecar({required String storagePath}) => RustLib
    .instance
    .api
    .crateApiWalletEthApiArgosWipeMnemonicSidecar(storagePath: storagePath);
