name: phantomchat
description: PhantomChat — decentralized encrypted messenger
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.4
  local_auth: ^2.3.0
  cupertino_icons: ^1.0.8
  flutter_rust_bridge: 2.12.0
  freezed_annotation: ^2.4.4
  # Wave 8B — background relay-listener
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/

