// Tests for PhantomContact.fromPhantomId — the QR-import / manual-add
// parser. Three wire shapes are accepted:
//
//   * `phantom:<view_hex>:<spend_hex>` — the canonical Desktop V3 format.
//   * `phantomx:<view_hex>:<spend_hex>:<mlkem_b64>` — hybrid PQXDH path;
//     mobile drops the mlkem segment for now (send-path doesn't yet emit
//     hybrid envelopes) but the contact still imports.
//   * legacy base64-JSON — `phantom:<base64url-of-{vk,sk,n}>` for
//     mobile↔mobile QR codes generated by older builds.
//
// Anything that doesn't match exactly one of the above must return null
// rather than crash — the QR scanner feeds raw camera output in.

import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:phantomchat/models/contact.dart';

void main() {
  // Two valid 64-char hex strings (32-byte ed25519 pubkeys, formatted
  // exactly as core::address::PhantomAddress::Display emits them).
  const viewHex =
      '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
  const spendHex =
      'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210';

  group('canonical phantom:<view>:<spend>', () {
    test('imports with both keys populated', () {
      final c = PhantomContact.fromPhantomId(
        'phantom:$viewHex:$spendHex',
        'alice',
      );
      expect(c, isNotNull);
      expect(c!.nickname, 'alice');
      expect(c.publicViewKey, viewHex);
      expect(c.publicSpendKey, spendHex);
      // Spend key doubles as the contact id (matches Desktop side).
      expect(c.id, spendHex);
    });

    test('whitespace is trimmed', () {
      final c = PhantomContact.fromPhantomId(
        '  phantom:$viewHex:$spendHex  ',
        'bob',
      );
      expect(c, isNotNull);
      expect(c!.publicSpendKey, spendHex);
    });

    test('uppercase hex still parses', () {
      final c = PhantomContact.fromPhantomId(
        'phantom:${viewHex.toUpperCase()}:${spendHex.toUpperCase()}',
        'carol',
      );
      expect(c, isNotNull);
    });
  });

  group('hybrid phantomx:<view>:<spend>:<mlkem>', () {
    test('imports with view+spend stored, mlkem segment ignored', () {
      // Real mlkem b64 would be ~1.5 KB; we only need *some* base64 here
      // since the mobile parser drops the segment.
      final mlkem = base64Url.encode(List<int>.filled(64, 0xAA));
      final c = PhantomContact.fromPhantomId(
        'phantomx:$viewHex:$spendHex:$mlkem',
        'dave',
      );
      expect(c, isNotNull);
      expect(c!.publicViewKey, viewHex);
      expect(c.publicSpendKey, spendHex);
    });

    test('rejects malformed hybrid (only one hex segment)', () {
      expect(
        PhantomContact.fromPhantomId('phantomx:$viewHex', 'eve'),
        isNull,
      );
    });

    test('rejects hybrid with non-hex view key', () {
      expect(
        PhantomContact.fromPhantomId(
          'phantomx:not-hex-not-hex-not-hex-not-hex-not-hex-not-hex-not-hex-not-hex:$spendHex:abcd',
          'eve',
        ),
        isNull,
      );
    });
  });

  group('legacy base64-JSON', () {
    test('imports {vk,sk,n} payload', () {
      final json = jsonEncode({'vk': viewHex, 'sk': spendHex, 'n': 'X'});
      final body = base64Url.encode(utf8.encode(json));
      final c = PhantomContact.fromPhantomId('phantom:$body', 'frank');
      expect(c, isNotNull);
      expect(c!.publicViewKey, viewHex);
      expect(c.publicSpendKey, spendHex);
      expect(c.id, spendHex);
    });

    test('legacy JSON missing vk → null', () {
      final json = jsonEncode({'sk': spendHex, 'n': 'X'});
      final body = base64Url.encode(utf8.encode(json));
      expect(
        PhantomContact.fromPhantomId('phantom:$body', 'gus'),
        isNull,
      );
    });
  });

  group('garbage', () {
    test('empty string → null', () {
      expect(PhantomContact.fromPhantomId('', 'x'), isNull);
    });

    test('non-phantom URL → null', () {
      expect(
        PhantomContact.fromPhantomId(
          'https://example.com/whatever',
          'x',
        ),
        isNull,
      );
    });

    test('phantom: with too-short hex → null', () {
      expect(
        PhantomContact.fromPhantomId('phantom:dead:beef', 'x'),
        isNull,
      );
    });

    test('phantom: with non-hex chars → null', () {
      // 64 chars but contains a 'z' (not hex).
      final bad = 'z' * 64;
      expect(
        PhantomContact.fromPhantomId('phantom:$bad:$spendHex', 'x'),
        isNull,
      );
    });

    test('plain text → null', () {
      expect(
        PhantomContact.fromPhantomId('just some random text', 'x'),
        isNull,
      );
    });
  });
}
