// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cache`, `map_network`, `preview_cache`, `unlocked`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Generate a fresh wallet, persist it encrypted with `pin` to `storage_path`,
/// and return the recovery mnemonic. The mnemonic MUST be displayed to the
/// user exactly once for backup; the app should treat it as write-only.
Future<ArgosWalletInfo> argosCreateWallet({
  required String network,
  required String pin,
  required String storagePath,
}) => RustLib.instance.api.crateApiWalletArgosCreateWallet(
  network: network,
  pin: pin,
  storagePath: storagePath,
);

/// Restore from a user-typed 12/24-word BIP39 mnemonic, persist encrypted,
/// and unlock in one step. Use during onboarding after a wipe.
Future<ArgosWalletInfo> argosRestoreWallet({
  required String mnemonic,
  required String network,
  required String pin,
  required String storagePath,
}) => RustLib.instance.api.crateApiWalletArgosRestoreWallet(
  mnemonic: mnemonic,
  network: network,
  pin: pin,
  storagePath: storagePath,
);

/// Unlock an existing on-disk wallet with `pin`. Returns the pubkey on
/// success. Wrong PIN surfaces as `Err("wrong PIN")`.
Future<String> argosUnlockWallet({
  required String pin,
  required String storagePath,
}) => RustLib.instance.api.crateApiWalletArgosUnlockWallet(
  pin: pin,
  storagePath: storagePath,
);

/// Wipe the cached wallet from RAM. Idempotent — safe to call when already
/// locked.
Future<void> argosLockWallet() =>
    RustLib.instance.api.crateApiWalletArgosLockWallet();

/// Returns Some(pubkey_b58) when a wallet is currently unlocked.
String? argosWalletPubkey() =>
    RustLib.instance.api.crateApiWalletArgosWalletPubkey();

/// Active network ("mainnet-beta" or "devnet") of the unlocked wallet.
String? argosWalletNetwork() =>
    RustLib.instance.api.crateApiWalletArgosWalletNetwork();

/// Native SOL balance in lamports.
Future<BigInt> argosBalanceSol() =>
    RustLib.instance.api.crateApiWalletArgosBalanceSol();

/// SPL token balance for `mint_b58`, in raw token units (no decimal conversion).
Future<BigInt> argosBalanceToken({required String mintB58}) =>
    RustLib.instance.api.crateApiWalletArgosBalanceToken(mintB58: mintB58);

/// Send `lamports` of native SOL to `recipient_b58`. Returns the confirmed
/// signature (base58, links to Solscan).
Future<String> argosSendSol({
  required String recipientB58,
  required BigInt lamports,
}) => RustLib.instance.api.crateApiWalletArgosSendSol(
  recipientB58: recipientB58,
  lamports: lamports,
);

/// Send `amount` raw units of `mint_b58` SPL token to `recipient_b58`.
/// Auto-creates the recipient's ATA if missing (sender pays ~0.002 SOL rent).
Future<String> argosSendToken({
  required String mintB58,
  required String recipientB58,
  required BigInt amount,
}) => RustLib.instance.api.crateApiWalletArgosSendToken(
  mintB58: mintB58,
  recipientB58: recipientB58,
  amount: amount,
);

/// Ask Jupiter for the best swap route. Caches the full preview Rust-side
/// so `argos_execute_swap` / `argos_swap_and_send` don't need to round-trip
/// the raw quote JSON across the FFI border.
Future<ArgosSwapPreview> argosQuoteSwap({
  required String inputMintB58,
  required String outputMintB58,
  required BigInt amountIn,
  required int slippageBps,
}) => RustLib.instance.api.crateApiWalletArgosQuoteSwap(
  inputMintB58: inputMintB58,
  outputMintB58: outputMintB58,
  amountIn: amountIn,
  slippageBps: slippageBps,
);

/// Execute the most recently quoted swap. Output stays in the user's wallet.
Future<String> argosExecuteSwap() =>
    RustLib.instance.api.crateApiWalletArgosExecuteSwap();

/// **Auto-Swap-on-Send** — Argos killer feature.
///
/// Atomic single-tx: swap `input_mint` → `output_mint`, deliver to
/// `recipient_b58` directly, collect 0.5 % platform fee. Uses the cached
/// preview from the previous `argos_quote_swap` call.
Future<ArgosSwapAndSendOutcome> argosSwapAndSend({
  required String recipientB58,
}) => RustLib.instance.api.crateApiWalletArgosSwapAndSend(
  recipientB58: recipientB58,
);

/// Validate a user-pasted Solana address. Returns the canonical base58
/// form on success, or a friendly error message on parse failure.
String argosValidateAddress({required String s}) =>
    RustLib.instance.api.crateApiWalletArgosValidateAddress(s: s);

/// Request a 1 SOL airdrop on Devnet — for QA only. Fails on Mainnet.
Future<String> argosDevnetAirdropOneSol() =>
    RustLib.instance.api.crateApiWalletArgosDevnetAirdropOneSol();

/// Result of `argos_swap_and_send` — the killer Auto-Swap-on-Send feature.
class ArgosSwapAndSendOutcome {
  /// Confirmed transaction signature (base58, links to Solscan).
  final String signatureB58;

  /// Recipient's associated token account that received the swap output.
  final String recipientAtaB58;

  /// Mint the recipient received.
  final String outputMintB58;

  /// Expected output amount delivered (pre-slippage).
  final BigInt amountOutExpected;

  const ArgosSwapAndSendOutcome({
    required this.signatureB58,
    required this.recipientAtaB58,
    required this.outputMintB58,
    required this.amountOutExpected,
  });

  @override
  int get hashCode =>
      signatureB58.hashCode ^
      recipientAtaB58.hashCode ^
      outputMintB58.hashCode ^
      amountOutExpected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArgosSwapAndSendOutcome &&
          runtimeType == other.runtimeType &&
          signatureB58 == other.signatureB58 &&
          recipientAtaB58 == other.recipientAtaB58 &&
          outputMintB58 == other.outputMintB58 &&
          amountOutExpected == other.amountOutExpected;
}

/// UI-side projection of [`argos_wallet::swap::SwapPreview`]. The full
/// preview is stored Rust-side via `PREVIEW_CACHE`; the Dart layer just
/// keeps the human-readable fields.
class ArgosSwapPreview {
  /// Raw amount the user pays, in input-mint smallest units.
  final BigInt amountIn;

  /// Min output amount, in output-mint smallest units (post-slippage).
  final BigInt amountOutMin;

  /// Expected (mid-point) output, in output-mint smallest units.
  final BigInt amountOutExpected;

  /// Platform fee, in output-mint smallest units (0.5 % of output).
  final BigInt platformFeeOut;

  /// Best-effort human route summary, e.g. "Raydium → Orca".
  final String routeLabel;

  /// Slippage tolerance in basis points (50 = 0.5 %).
  final int slippageBps;

  /// Output mint (for Dart-side display of "you receive X of mint Y").
  final String outputMintB58;

  const ArgosSwapPreview({
    required this.amountIn,
    required this.amountOutMin,
    required this.amountOutExpected,
    required this.platformFeeOut,
    required this.routeLabel,
    required this.slippageBps,
    required this.outputMintB58,
  });

  @override
  int get hashCode =>
      amountIn.hashCode ^
      amountOutMin.hashCode ^
      amountOutExpected.hashCode ^
      platformFeeOut.hashCode ^
      routeLabel.hashCode ^
      slippageBps.hashCode ^
      outputMintB58.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArgosSwapPreview &&
          runtimeType == other.runtimeType &&
          amountIn == other.amountIn &&
          amountOutMin == other.amountOutMin &&
          amountOutExpected == other.amountOutExpected &&
          platformFeeOut == other.platformFeeOut &&
          routeLabel == other.routeLabel &&
          slippageBps == other.slippageBps &&
          outputMintB58 == other.outputMintB58;
}

/// What the UI shows on wallet creation / restore. Mnemonic is ONLY
/// populated on `create` and `restore` — never on `unlock`, so an unlocked
/// session can't re-leak the recovery phrase.
class ArgosWalletInfo {
  /// Solana public key (base58, the Solscan-friendly form).
  final String pubkeyB58;

  /// BIP39 mnemonic — 24 English words separated by single spaces.
  /// Empty on `unlock_wallet`; non-empty on `create_wallet` and `restore_wallet`.
  final String mnemonic;

  /// Network the wallet was created against.
  final String network;

  const ArgosWalletInfo({
    required this.pubkeyB58,
    required this.mnemonic,
    required this.network,
  });

  @override
  int get hashCode => pubkeyB58.hashCode ^ mnemonic.hashCode ^ network.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArgosWalletInfo &&
          runtimeType == other.runtimeType &&
          pubkeyB58 == other.pubkeyB58 &&
          mnemonic == other.mnemonic &&
          network == other.network;
}
