import 'package:shared_preferences/shared_preferences.dart';
// Generated by flutter_rust_bridge_codegen from core/src/api.rs::set_privacy_mode()
// Run: flutter_rust_bridge_codegen generate
import 'package:mobile/src/rust/api.dart' as rust;

/// Privacy modes matching the Rust `PrivacyMode` enum.
enum PrivacyMode { dailyUse, maximumStealth }

/// Thin service layer between the UI and the Rust privacy API.
///
/// Persists the last-used mode across restarts via SharedPreferences so the
/// UI can render the correct state before the Rust bridge is ready.
class PrivacyService {
  static const _kMode      = 'privacy_mode';
  static const _kProxyAddr = 'proxy_addr';
  static const _kUseNym    = 'use_nym';

  static const String defaultTorProxy = '127.0.0.1:9050';
  static const String defaultNymProxy = '127.0.0.1:1080';

  /// Load persisted mode from SharedPreferences.
  static Future<PrivacyMode> loadMode() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_kMode) ?? 'dailyUse';
    return raw == 'maximumStealth' ? PrivacyMode.maximumStealth : PrivacyMode.dailyUse;
  }

  /// Persist mode and apply it via the Rust bridge.
  ///
  /// Returns `null` on success, or an error message string.
  static Future<String?> setMode({
    required PrivacyMode mode,
    String?  proxyAddr,
    bool     useNym = false,
  }) async {
    final modeStr = mode == PrivacyMode.maximumStealth ? 'stealth' : 'daily';
    final proxy   = proxyAddr ?? (useNym ? defaultNymProxy : defaultTorProxy);

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_kMode, mode == PrivacyMode.maximumStealth ? 'maximumStealth' : 'dailyUse');
    await prefs.setString(_kProxyAddr, proxy);
    await prefs.setBool(_kUseNym, useNym);

    try {
      final result = rust.setPrivacyMode(
        modeStr:   modeStr,
        proxyAddr: proxy,
        useNym:    useNym,
      );
      if (result.startsWith('ERROR')) return result;
      return null;
    } catch (e) {
      return e.toString();
    }
  }

  /// Reads the current mode directly from the Rust layer.
  static String getRustMode() {
    try {
      return rust.getPrivacyMode();
    } catch (_) {
      return 'DailyUse';
    }
  }

  static Future<String> loadProxyAddr() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_kProxyAddr) ?? defaultTorProxy;
  }

  static Future<bool> loadUseNym() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getBool(_kUseNym) ?? false;
  }
}
