// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IdentityKeys`, `PhysicalSecureMessage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<String> initSecureStorage(
        {required String dbPath, required String password}) =>
    RustLib.instance.api
        .crateApiInitSecureStorage(dbPath: dbPath, password: password);

Future<String> generatePhantomId() =>
    RustLib.instance.api.crateApiGeneratePhantomId();

Stream<NetworkEvent> startNetworkNode({String? avatarCid}) =>
    RustLib.instance.api.crateApiStartNetworkNode(avatarCid: avatarCid);

Future<void> sendSecureMessage(
        {required String targetPeerId,
        required String phantomId,
        required String message}) =>
    RustLib.instance.api.crateApiSendSecureMessage(
        targetPeerId: targetPeerId, phantomId: phantomId, message: message);

Future<void> joinGroup({required String groupId}) =>
    RustLib.instance.api.crateApiJoinGroup(groupId: groupId);

Future<void> sendGroupMessage(
        {required String groupId, required String message}) =>
    RustLib.instance.api
        .crateApiSendGroupMessage(groupId: groupId, message: message);

Future<void> updateAvatarCid({required String cid}) =>
    RustLib.instance.api.crateApiUpdateAvatarCid(cid: cid);

Future<void> performPanicWipe({required String dbPath}) =>
    RustLib.instance.api.crateApiPerformPanicWipe(dbPath: dbPath);
