// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1074652651;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'phantomchat_mobile',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiGeneratePhantomId();

  String crateApiGetPrivacyMode();

  Future<String> crateApiInitSecureStorage({
    required String dbPath,
    required String password,
  });

  Future<void> crateApiJoinGroup({required String groupId});

  Future<String> crateApiLoadLocalIdentity({
    required String viewSecretHex,
    required String spendSecretHex,
  });

  Future<String> crateApiLoadLocalIdentityV3({
    required String viewSecretHex,
    required String spendSecretHex,
    required String signingSecretHex,
  });

  Future<(Uint8List, Uint8List)> crateApiMlsAddMember({
    required List<int> keyPackageBytes,
    required String newMemberLabel,
    required String newMemberAddress,
    required String newMemberSigningPubHex,
  });

  Future<int> crateApiMlsCreateGroup();

  Future<Uint8List?> crateApiMlsDecrypt({required List<int> wireBytes});

  Future<List<MlsMemberRefV3>> crateApiMlsDirectory();

  Future<void> crateApiMlsDirectoryInsert({
    required String label,
    required String address,
    required String signingPubHex,
  });

  Future<Uint8List> crateApiMlsEncrypt({required List<int> plaintext});

  bool crateApiMlsInGroup();

  Future<String> crateApiMlsInit({
    required String identityLabel,
    required String storageDir,
  });

  Future<int> crateApiMlsJoinViaWelcome({required List<int> welcomeBytes});

  Future<List<MlsMemberInfoV3>> crateApiMlsListMembers();

  int crateApiMlsMemberCount();

  Future<Uint8List> crateApiMlsPublishKeyPackage();

  String? crateApiMlsSelfLabel();

  Future<String> crateApiMlsSelfSigningPubHex();

  Future<NostrEventWire> crateApiNostrBuildEvent({
    required List<int> envelopeBytes,
  });

  Future<Uint8List?> crateApiNostrExtractEventPayload({
    required String frameText,
  });

  Future<String> crateApiNostrSubscriptionReq({required String subId});

  Future<void> crateApiPerformPanicWipe({required String dbPath});

  Future<ReceivedFullV3?> crateApiReceiveFullV3({required List<int> wireBytes});

  Future<Uint8List?> crateApiScanIncomingEnvelope({
    required List<int> wireBytes,
  });

  Future<void> crateApiSendGroupMessage({
    required String groupId,
    required String message,
  });

  Future<Uint8List> crateApiSendSealedV3({
    required String recipientAddress,
    required List<int> plaintext,
  });

  Future<String> crateApiSendSecureMessage({
    required String recipientAddress,
    required String localPhantomId,
    required String plaintext,
  });

  String crateApiSetPrivacyMode({
    required String modeStr,
    String? proxyAddr,
    required bool useNym,
  });

  Future<void> crateApiUpdateAvatarCid({required String cid});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiGeneratePhantomId() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGeneratePhantomIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGeneratePhantomIdConstMeta =>
      const TaskConstMeta(debugName: "generate_phantom_id", argNames: []);

  @override
  String crateApiGetPrivacyMode() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetPrivacyModeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPrivacyModeConstMeta =>
      const TaskConstMeta(debugName: "get_privacy_mode", argNames: []);

  @override
  Future<String> crateApiInitSecureStorage({
    required String dbPath,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitSecureStorageConstMeta,
        argValues: [dbPath, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitSecureStorageConstMeta => const TaskConstMeta(
    debugName: "init_secure_storage",
    argNames: ["dbPath", "password"],
  );

  @override
  Future<void> crateApiJoinGroup({required String groupId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJoinGroupConstMeta,
        argValues: [groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJoinGroupConstMeta =>
      const TaskConstMeta(debugName: "join_group", argNames: ["groupId"]);

  @override
  Future<String> crateApiLoadLocalIdentity({
    required String viewSecretHex,
    required String spendSecretHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(viewSecretHex, serializer);
          sse_encode_String(spendSecretHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoadLocalIdentityConstMeta,
        argValues: [viewSecretHex, spendSecretHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadLocalIdentityConstMeta => const TaskConstMeta(
    debugName: "load_local_identity",
    argNames: ["viewSecretHex", "spendSecretHex"],
  );

  @override
  Future<String> crateApiLoadLocalIdentityV3({
    required String viewSecretHex,
    required String spendSecretHex,
    required String signingSecretHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(viewSecretHex, serializer);
          sse_encode_String(spendSecretHex, serializer);
          sse_encode_String(signingSecretHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoadLocalIdentityV3ConstMeta,
        argValues: [viewSecretHex, spendSecretHex, signingSecretHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadLocalIdentityV3ConstMeta =>
      const TaskConstMeta(
        debugName: "load_local_identity_v3",
        argNames: ["viewSecretHex", "spendSecretHex", "signingSecretHex"],
      );

  @override
  Future<(Uint8List, Uint8List)> crateApiMlsAddMember({
    required List<int> keyPackageBytes,
    required String newMemberLabel,
    required String newMemberAddress,
    required String newMemberSigningPubHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(keyPackageBytes, serializer);
          sse_encode_String(newMemberLabel, serializer);
          sse_encode_String(newMemberAddress, serializer);
          sse_encode_String(newMemberSigningPubHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_record_list_prim_u_8_strict_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsAddMemberConstMeta,
        argValues: [
          keyPackageBytes,
          newMemberLabel,
          newMemberAddress,
          newMemberSigningPubHex,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsAddMemberConstMeta => const TaskConstMeta(
    debugName: "mls_add_member",
    argNames: [
      "keyPackageBytes",
      "newMemberLabel",
      "newMemberAddress",
      "newMemberSigningPubHex",
    ],
  );

  @override
  Future<int> crateApiMlsCreateGroup() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsCreateGroupConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsCreateGroupConstMeta =>
      const TaskConstMeta(debugName: "mls_create_group", argNames: []);

  @override
  Future<Uint8List?> crateApiMlsDecrypt({required List<int> wireBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(wireBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsDecryptConstMeta,
        argValues: [wireBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsDecryptConstMeta =>
      const TaskConstMeta(debugName: "mls_decrypt", argNames: ["wireBytes"]);

  @override
  Future<List<MlsMemberRefV3>> crateApiMlsDirectory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mls_member_ref_v_3,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsDirectoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsDirectoryConstMeta =>
      const TaskConstMeta(debugName: "mls_directory", argNames: []);

  @override
  Future<void> crateApiMlsDirectoryInsert({
    required String label,
    required String address,
    required String signingPubHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(label, serializer);
          sse_encode_String(address, serializer);
          sse_encode_String(signingPubHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsDirectoryInsertConstMeta,
        argValues: [label, address, signingPubHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsDirectoryInsertConstMeta => const TaskConstMeta(
    debugName: "mls_directory_insert",
    argNames: ["label", "address", "signingPubHex"],
  );

  @override
  Future<Uint8List> crateApiMlsEncrypt({required List<int> plaintext}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsEncryptConstMeta,
        argValues: [plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsEncryptConstMeta =>
      const TaskConstMeta(debugName: "mls_encrypt", argNames: ["plaintext"]);

  @override
  bool crateApiMlsInGroup() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMlsInGroupConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsInGroupConstMeta =>
      const TaskConstMeta(debugName: "mls_in_group", argNames: []);

  @override
  Future<String> crateApiMlsInit({
    required String identityLabel,
    required String storageDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(identityLabel, serializer);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsInitConstMeta,
        argValues: [identityLabel, storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsInitConstMeta => const TaskConstMeta(
    debugName: "mls_init",
    argNames: ["identityLabel", "storageDir"],
  );

  @override
  Future<int> crateApiMlsJoinViaWelcome({required List<int> welcomeBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(welcomeBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsJoinViaWelcomeConstMeta,
        argValues: [welcomeBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsJoinViaWelcomeConstMeta => const TaskConstMeta(
    debugName: "mls_join_via_welcome",
    argNames: ["welcomeBytes"],
  );

  @override
  Future<List<MlsMemberInfoV3>> crateApiMlsListMembers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mls_member_info_v_3,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsListMembersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsListMembersConstMeta =>
      const TaskConstMeta(debugName: "mls_list_members", argNames: []);

  @override
  int crateApiMlsMemberCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMlsMemberCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsMemberCountConstMeta =>
      const TaskConstMeta(debugName: "mls_member_count", argNames: []);

  @override
  Future<Uint8List> crateApiMlsPublishKeyPackage() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsPublishKeyPackageConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsPublishKeyPackageConstMeta =>
      const TaskConstMeta(debugName: "mls_publish_key_package", argNames: []);

  @override
  String? crateApiMlsSelfLabel() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMlsSelfLabelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsSelfLabelConstMeta =>
      const TaskConstMeta(debugName: "mls_self_label", argNames: []);

  @override
  Future<String> crateApiMlsSelfSigningPubHex() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMlsSelfSigningPubHexConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMlsSelfSigningPubHexConstMeta =>
      const TaskConstMeta(debugName: "mls_self_signing_pub_hex", argNames: []);

  @override
  Future<NostrEventWire> crateApiNostrBuildEvent({
    required List<int> envelopeBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(envelopeBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_nostr_event_wire,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrBuildEventConstMeta,
        argValues: [envelopeBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrBuildEventConstMeta => const TaskConstMeta(
    debugName: "nostr_build_event",
    argNames: ["envelopeBytes"],
  );

  @override
  Future<Uint8List?> crateApiNostrExtractEventPayload({
    required String frameText,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(frameText, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNostrExtractEventPayloadConstMeta,
        argValues: [frameText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrExtractEventPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_extract_event_payload",
        argNames: ["frameText"],
      );

  @override
  Future<String> crateApiNostrSubscriptionReq({required String subId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(subId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostrSubscriptionReqConstMeta,
        argValues: [subId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrSubscriptionReqConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_subscription_req",
        argNames: ["subId"],
      );

  @override
  Future<void> crateApiPerformPanicWipe({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPerformPanicWipeConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPerformPanicWipeConstMeta => const TaskConstMeta(
    debugName: "perform_panic_wipe",
    argNames: ["dbPath"],
  );

  @override
  Future<ReceivedFullV3?> crateApiReceiveFullV3({
    required List<int> wireBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(wireBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_received_full_v_3,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReceiveFullV3ConstMeta,
        argValues: [wireBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReceiveFullV3ConstMeta => const TaskConstMeta(
    debugName: "receive_full_v3",
    argNames: ["wireBytes"],
  );

  @override
  Future<Uint8List?> crateApiScanIncomingEnvelope({
    required List<int> wireBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(wireBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanIncomingEnvelopeConstMeta,
        argValues: [wireBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanIncomingEnvelopeConstMeta =>
      const TaskConstMeta(
        debugName: "scan_incoming_envelope",
        argNames: ["wireBytes"],
      );

  @override
  Future<void> crateApiSendGroupMessage({
    required String groupId,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(groupId, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSendGroupMessageConstMeta,
        argValues: [groupId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendGroupMessageConstMeta => const TaskConstMeta(
    debugName: "send_group_message",
    argNames: ["groupId", "message"],
  );

  @override
  Future<Uint8List> crateApiSendSealedV3({
    required String recipientAddress,
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recipientAddress, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendSealedV3ConstMeta,
        argValues: [recipientAddress, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSealedV3ConstMeta => const TaskConstMeta(
    debugName: "send_sealed_v3",
    argNames: ["recipientAddress", "plaintext"],
  );

  @override
  Future<String> crateApiSendSecureMessage({
    required String recipientAddress,
    required String localPhantomId,
    required String plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recipientAddress, serializer);
          sse_encode_String(localPhantomId, serializer);
          sse_encode_String(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSendSecureMessageConstMeta,
        argValues: [recipientAddress, localPhantomId, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSecureMessageConstMeta => const TaskConstMeta(
    debugName: "send_secure_message",
    argNames: ["recipientAddress", "localPhantomId", "plaintext"],
  );

  @override
  String crateApiSetPrivacyMode({
    required String modeStr,
    String? proxyAddr,
    required bool useNym,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modeStr, serializer);
          sse_encode_opt_String(proxyAddr, serializer);
          sse_encode_bool(useNym, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetPrivacyModeConstMeta,
        argValues: [modeStr, proxyAddr, useNym],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetPrivacyModeConstMeta => const TaskConstMeta(
    debugName: "set_privacy_mode",
    argNames: ["modeStr", "proxyAddr", "useNym"],
  );

  @override
  Future<void> crateApiUpdateAvatarCid({required String cid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUpdateAvatarCidConstMeta,
        argValues: [cid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateAvatarCidConstMeta =>
      const TaskConstMeta(debugName: "update_avatar_cid", argNames: ["cid"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ReceivedFullV3 dco_decode_box_autoadd_received_full_v_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_received_full_v_3(raw);
  }

  @protected
  List<MlsMemberInfoV3> dco_decode_list_mls_member_info_v_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mls_member_info_v_3).toList();
  }

  @protected
  List<MlsMemberRefV3> dco_decode_list_mls_member_ref_v_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mls_member_ref_v_3).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MlsMemberInfoV3 dco_decode_mls_member_info_v_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MlsMemberInfoV3(
      credentialLabel: dco_decode_String(arr[0]),
      signaturePubHex: dco_decode_String(arr[1]),
      isSelf: dco_decode_bool(arr[2]),
      mappedContactLabel: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  MlsMemberRefV3 dco_decode_mls_member_ref_v_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MlsMemberRefV3(
      label: dco_decode_String(arr[0]),
      address: dco_decode_String(arr[1]),
      signingPubHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  NostrEventWire dco_decode_nostr_event_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NostrEventWire(
      publishJson: dco_decode_String(arr[0]),
      eventId: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ReceivedFullV3? dco_decode_opt_box_autoadd_received_full_v_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_received_full_v_3(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  ReceivedFullV3 dco_decode_received_full_v_3(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReceivedFullV3(
      plaintext: dco_decode_list_prim_u_8_strict(arr[0]),
      senderPubHex: dco_decode_opt_String(arr[1]),
      sigOk: dco_decode_bool(arr[2]),
    );
  }

  @protected
  (Uint8List, Uint8List)
  dco_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_list_prim_u_8_strict(arr[0]),
      dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ReceivedFullV3 sse_decode_box_autoadd_received_full_v_3(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_received_full_v_3(deserializer));
  }

  @protected
  List<MlsMemberInfoV3> sse_decode_list_mls_member_info_v_3(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MlsMemberInfoV3>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mls_member_info_v_3(deserializer));
    }
    return ans_;
  }

  @protected
  List<MlsMemberRefV3> sse_decode_list_mls_member_ref_v_3(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MlsMemberRefV3>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mls_member_ref_v_3(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MlsMemberInfoV3 sse_decode_mls_member_info_v_3(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_credentialLabel = sse_decode_String(deserializer);
    var var_signaturePubHex = sse_decode_String(deserializer);
    var var_isSelf = sse_decode_bool(deserializer);
    var var_mappedContactLabel = sse_decode_opt_String(deserializer);
    return MlsMemberInfoV3(
      credentialLabel: var_credentialLabel,
      signaturePubHex: var_signaturePubHex,
      isSelf: var_isSelf,
      mappedContactLabel: var_mappedContactLabel,
    );
  }

  @protected
  MlsMemberRefV3 sse_decode_mls_member_ref_v_3(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_signingPubHex = sse_decode_String(deserializer);
    return MlsMemberRefV3(
      label: var_label,
      address: var_address,
      signingPubHex: var_signingPubHex,
    );
  }

  @protected
  NostrEventWire sse_decode_nostr_event_wire(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publishJson = sse_decode_String(deserializer);
    var var_eventId = sse_decode_String(deserializer);
    return NostrEventWire(publishJson: var_publishJson, eventId: var_eventId);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReceivedFullV3? sse_decode_opt_box_autoadd_received_full_v_3(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_received_full_v_3(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReceivedFullV3 sse_decode_received_full_v_3(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_plaintext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_senderPubHex = sse_decode_opt_String(deserializer);
    var var_sigOk = sse_decode_bool(deserializer);
    return ReceivedFullV3(
      plaintext: var_plaintext,
      senderPubHex: var_senderPubHex,
      sigOk: var_sigOk,
    );
  }

  @protected
  (Uint8List, Uint8List)
  sse_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
    var var_field1 = sse_decode_list_prim_u_8_strict(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_received_full_v_3(
    ReceivedFullV3 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_received_full_v_3(self, serializer);
  }

  @protected
  void sse_encode_list_mls_member_info_v_3(
    List<MlsMemberInfoV3> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mls_member_info_v_3(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mls_member_ref_v_3(
    List<MlsMemberRefV3> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mls_member_ref_v_3(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mls_member_info_v_3(
    MlsMemberInfoV3 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.credentialLabel, serializer);
    sse_encode_String(self.signaturePubHex, serializer);
    sse_encode_bool(self.isSelf, serializer);
    sse_encode_opt_String(self.mappedContactLabel, serializer);
  }

  @protected
  void sse_encode_mls_member_ref_v_3(
    MlsMemberRefV3 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_String(self.signingPubHex, serializer);
  }

  @protected
  void sse_encode_nostr_event_wire(
    NostrEventWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.publishJson, serializer);
    sse_encode_String(self.eventId, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_received_full_v_3(
    ReceivedFullV3? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_received_full_v_3(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_received_full_v_3(
    ReceivedFullV3 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.plaintext, serializer);
    sse_encode_opt_String(self.senderPubHex, serializer);
    sse_encode_bool(self.sigOk, serializer);
  }

  @protected
  void sse_encode_record_list_prim_u_8_strict_list_prim_u_8_strict(
    (Uint8List, Uint8List) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.$1, serializer);
    sse_encode_list_prim_u_8_strict(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
