// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 597586265;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'phantomchat_core',
    ioDirectory: '../core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiGeneratePhantomId();

  Future<String> crateApiInitSecureStorage(
      {required String dbPath, required String password});

  Future<void> crateApiJoinGroup({required String groupId});

  Future<void> crateApiPerformPanicWipe({required String dbPath});

  Future<void> crateApiSendGroupMessage(
      {required String groupId, required String message});

  Future<void> crateApiSendSecureMessage(
      {required String targetPeerId,
      required String phantomId,
      required String message});

  Stream<NetworkEvent> crateApiStartNetworkNode({String? avatarCid});

  Future<void> crateApiUpdateAvatarCid({required String cid});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiGeneratePhantomId() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGeneratePhantomIdConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGeneratePhantomIdConstMeta => const TaskConstMeta(
        debugName: "generate_phantom_id",
        argNames: [],
      );

  @override
  Future<String> crateApiInitSecureStorage(
      {required String dbPath, required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitSecureStorageConstMeta,
      argValues: [dbPath, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitSecureStorageConstMeta => const TaskConstMeta(
        debugName: "init_secure_storage",
        argNames: ["dbPath", "password"],
      );

  @override
  Future<void> crateApiJoinGroup({required String groupId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(groupId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiJoinGroupConstMeta,
      argValues: [groupId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiJoinGroupConstMeta => const TaskConstMeta(
        debugName: "join_group",
        argNames: ["groupId"],
      );

  @override
  Future<void> crateApiPerformPanicWipe({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPerformPanicWipeConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPerformPanicWipeConstMeta => const TaskConstMeta(
        debugName: "perform_panic_wipe",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateApiSendGroupMessage(
      {required String groupId, required String message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(groupId, serializer);
        sse_encode_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSendGroupMessageConstMeta,
      argValues: [groupId, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendGroupMessageConstMeta => const TaskConstMeta(
        debugName: "send_group_message",
        argNames: ["groupId", "message"],
      );

  @override
  Future<void> crateApiSendSecureMessage(
      {required String targetPeerId,
      required String phantomId,
      required String message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(targetPeerId, serializer);
        sse_encode_String(phantomId, serializer);
        sse_encode_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSendSecureMessageConstMeta,
      argValues: [targetPeerId, phantomId, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSendSecureMessageConstMeta => const TaskConstMeta(
        debugName: "send_secure_message",
        argNames: ["targetPeerId", "phantomId", "message"],
      );

  @override
  Stream<NetworkEvent> crateApiStartNetworkNode({String? avatarCid}) {
    final sink = RustStreamSink<NetworkEvent>();
    handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_network_event_Sse(sink, serializer);
        sse_encode_opt_String(avatarCid, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStartNetworkNodeConstMeta,
      argValues: [sink, avatarCid],
      apiImpl: this,
    ));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStartNetworkNodeConstMeta => const TaskConstMeta(
        debugName: "start_network_node",
        argNames: ["sink", "avatarCid"],
      );

  @override
  Future<void> crateApiUpdateAvatarCid({required String cid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiUpdateAvatarCidConstMeta,
      argValues: [cid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateAvatarCidConstMeta => const TaskConstMeta(
        debugName: "update_avatar_cid",
        argNames: ["cid"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<NetworkEvent> dco_decode_StreamSink_network_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NetworkEvent dco_decode_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NetworkEvent_NodeStarted(
          peerId: dco_decode_String(raw[1]),
        );
      case 1:
        return NetworkEvent_PeerDiscovered(
          peerId: dco_decode_String(raw[1]),
          avatarCid: dco_decode_opt_String(raw[2]),
        );
      case 2:
        return NetworkEvent_MessageReceived(
          from: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 3:
        return NetworkEvent_GroupMessageReceived(
          groupId: dco_decode_String(raw[1]),
          from: dco_decode_String(raw[2]),
          message: dco_decode_String(raw[3]),
        );
      case 4:
        return NetworkEvent_Error(
          message: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<NetworkEvent> sse_decode_StreamSink_network_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NetworkEvent sse_decode_network_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_peerId = sse_decode_String(deserializer);
        return NetworkEvent_NodeStarted(peerId: var_peerId);
      case 1:
        var var_peerId = sse_decode_String(deserializer);
        var var_avatarCid = sse_decode_opt_String(deserializer);
        return NetworkEvent_PeerDiscovered(
            peerId: var_peerId, avatarCid: var_avatarCid);
      case 2:
        var var_from = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return NetworkEvent_MessageReceived(
            from: var_from, message: var_message);
      case 3:
        var var_groupId = sse_decode_String(deserializer);
        var var_from = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return NetworkEvent_GroupMessageReceived(
            groupId: var_groupId, from: var_from, message: var_message);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return NetworkEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_network_event_Sse(
      RustStreamSink<NetworkEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_network_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_network_event(NetworkEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NetworkEvent_NodeStarted(peerId: final peerId):
        sse_encode_i_32(0, serializer);
        sse_encode_String(peerId, serializer);
      case NetworkEvent_PeerDiscovered(
          peerId: final peerId,
          avatarCid: final avatarCid
        ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(peerId, serializer);
        sse_encode_opt_String(avatarCid, serializer);
      case NetworkEvent_MessageReceived(
          from: final from,
          message: final message
        ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(from, serializer);
        sse_encode_String(message, serializer);
      case NetworkEvent_GroupMessageReceived(
          groupId: final groupId,
          from: final from,
          message: final message
        ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(groupId, serializer);
        sse_encode_String(from, serializer);
        sse_encode_String(message, serializer);
      case NetworkEvent_Error(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
