// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'network.freezed.dart';

@freezed
sealed class NetworkEvent with _$NetworkEvent {
  const NetworkEvent._();

  const factory NetworkEvent.nodeStarted({required String peerId}) =
      NetworkEvent_NodeStarted;
  const factory NetworkEvent.peerDiscovered({
    required String peerId,
    String? avatarCid,
  }) = NetworkEvent_PeerDiscovered;
  const factory NetworkEvent.messageReceived({
    required String from,
    required String message,
  }) = NetworkEvent_MessageReceived;
  const factory NetworkEvent.groupMessageReceived({
    required String groupId,
    required String from,
    required String message,
  }) = NetworkEvent_GroupMessageReceived;
  const factory NetworkEvent.error({required String message}) =
      NetworkEvent_Error;
}
